codeBase/webServices/core/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static
from web_app import views as web_app_views
urlpatterns = [
    path("dashboard/v1/", include('dashboard.urls', namespace="dashboard")),
    path("web_app/v1/", include('web_app.urls', namespace="web_app")),
    path("system_runtime_tracker/v1/", include('systemUptimeTracker.urls', namespace="systemUptimeTracker")),
    path("monitor_system_resource/v1/", include('monitor_system_resource.urls', namespace="monitor_system_resource")),
    path("admin/", admin.site.urls),
    path('tabler/', include('admin_tabler.urls')),
    path('service-worker.js', web_app_views.serve_service_worker_file, name="service-worker-file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codeBase/webServices/dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('home/', views.home_view, name='home'),

    path('get_time/', views.get_time, name='get_time'),
    path('systemStatus/', views.systemStatus, name='systemStatus'),
    path('dashboard_statistics/', views.dashboard_statistics, name='dashboard_statistics'),
    path('get_mqtt_broker_statistics/', views.get_mqtt_broker_statistics, name='get_mqtt_broker_statistics'),


    path('users/', views.dashboard_all_user_view, name='dashboard_all_users'),
    path('users/create_new_user/', views.dashboard_create_or_edit_user_view, name='dashboard_create_new_user'),
    path('users/edit/<uuid:user_uuid>/', views.dashboard_create_or_edit_user_view, name='dashboard_edit_user'),
    path('users/delete/<uuid:user_uuid>/', views.dashboard_delete_user_view, name='dashboard_delete_user'),

    path('amir/', views.amir, name='amir'),
    path('settings/', views.settings, name='settings'),
    path('settings_button1/', views.settings_button, name='settings_button1'),

    path('projects/all/', views.all_projects_view, name='projects_view'),
    path('projects/new_project/', views.create_or_edit_project, name='create_new_project'),
    path('projects/edit/<uuid:project_uuid>/', views.create_or_edit_project, name='edit_project'),
    path('projects/delete/<uuid:project_uuid>/', views.delete_project, name='delete_project'),
    # project Homes section
    path('projects/<uuid:project_uuid>/homes/all/', views.project_all_homes_view, name='project_all_homes'),

    path('projects/<uuid:project_uuid>/homes/new_home/', views.create_or_edit_home, name='create_new_home'),
    path('projects/<uuid:project_uuid>/homes/edit/<uuid:home_uuid>/', views.create_or_edit_home, name='edit_home'),
    path('projects/<uuid:project_uuid>/homes/delete/<uuid:home_uuid>/', views.delete_home, name='delete_home'),

    # home settings dedicated page
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/', views.view_selected_home_settings_page, name='home_wizards'),


    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/overview/', views.home_overview_view, name='home_overview'),

    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/settings/', views.home_general_settings_section_view, name='home_wizard_home_settings'),



    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/tablet/', views.home_tablet_section_view, name='home_wizard_tablet_settings'),



    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/users/', views.home_all_users_view, name='home_wizard_all_users'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/users/create_new_user/', views.create_or_edit_home_user_view, name='home_wizard_create_new_user'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/users/edit/<uuid:user_uuid>/', views.create_or_edit_home_user_view, name='home_wizard_edit_user'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/users/delete/<uuid:user_uuid>/', views.delete_home_user_view, name='home_wizard_delete_user'),

    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/zones/', views.home_all_zones_view, name='home_wizard_all_zones'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/zones/create_new_zone/', views.create_or_edit_home_zone_view, name='home_wizard_create_new_zone'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/zones/edit/<uuid:zone_uuid>/', views.create_or_edit_home_zone_view, name='home_wizard_edit_zone'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/zones/delete/<uuid:zone_uuid>/', views.delete_home_zone_view, name='home_wizard_delete_zone'),

    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/controllers/', views.home_all_controller_view, name='home_wizard_all_controllers'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/controllers/create_new_controller/', views.create_or_edit_home_controller_view, name='home_wizard_create_new_controller'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/controllers/edit/<uuid:controller_uuid>/', views.create_or_edit_home_controller_view, name='home_wizard_edit_controller'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/controllers/delete/<uuid:controller_uuid>/', views.delete_home_controller_view, name='home_wizard_delete_controller'),

    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/controllers/get_config/<uuid:controller_uuid>/',views.download_home_controller_config_view, name='home_wizard_download_controller_config'),


    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/devices/', views.home_all_devices_view, name='home_wizard_all_devices'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/devices/create_new_device/', views.create_or_edit_home_device_view, name='home_wizard_create_new_device'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/devices/edit/<uuid:device_uuid>/', views.create_or_edit_home_device_view, name='home_wizard_edit_device'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/devices/delete/<uuid:device_uuid>/', views.delete_home_device_view, name='home_wizard_delete_device'),



    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/ui/', views.home_all_ui_elements_view, name='home_wizard_all_ui_elements'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/ui/create_new_ui/', views.create_or_edit_home_ui_element_view, name='home_wizard_create_new_ui_element'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/ui/edit/<uuid:ui_element_uuid>/', views.create_or_edit_home_ui_element_view, name='home_wizard_edit_ui_element'),
    path('projects/<uuid:project_uuid>/homes/<uuid:home_uuid>/wizard/ui/delete/<uuid:ui_element_uuid>/', views.delete_home_ui_element_view, name='home_wizard_delete_ui_element'),



    path('actionForm/', views.manage_device_switch_actions, name='actionnnnn'),
    path('font/', views.font, name='actionnnnn'),
    path('actionForm2/', views.manage_device_actions, name='action2'),

    path('create_user/', views.create_user, name='create_user1'),
    path('pyodide/', views.pyodide, name='create_user1'),


]

codeBase/webServices/dashboard/models.py
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django_advance_thumbnail import AdvanceThumbnailField

from .utils import generate_random_password, generate_random_username, generate_random_id


def generate_rand_id_for_controller():
    return ''.join(["controller_", generate_random_id()])


def generate_rand_id_for_client():
    return ''.join(["client_", generate_random_id()])



class DashboardUser(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='dashboardUser', related_query_name='dashboardUser')
    avatar = models.ImageField(upload_to="dashboard_users_avatar/original_files/", blank=True, null=True)
    avatar_thumbnail = AdvanceThumbnailField(source_field='avatar', upload_to='dashboard_users_avatar/thumbnail_files/',
                                             null=True, blank=True, size=(300, 300))

    telegramID = models.CharField(max_length=100, default='', blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='dashboardUser', related_query_name='dashboardUser')



class CityCoordinates(models.Model):
    city_name = models.CharField(max_length=100, blank=False, null=False)
    longitude = models.CharField(max_length=100, blank=True, null=True)
    latitude = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.city_name}"


class Project(models.Model):
    class ProjectStatusChoices(models.TextChoices):
        DISABLE = 'disable', 'disable'
        ENABLE = 'enable', 'enable'
        IN_CONSTRUCTION = 'in_construction', 'construction'
        MAINTENANCE = 'maintenance', 'maintenance'

    project_name = models.CharField(max_length=100, blank=False, null=False)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)
    owner_name = models.CharField(max_length=100, blank=True, null=True)
    owner_phone_number = models.CharField(max_length=100, blank=True, null=True)
    descriptions = models.CharField(max_length=1000, blank=True, null=True)
    # used for web app/tablet. set default icon to artiman company icon.
    # project_icon = models.ImageField(upload_to="project_icons/")
    city = models.ForeignKey(CityCoordinates, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, blank=True, null=True)
    project_lock = models.BooleanField(blank=False, null=False, default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_created_by")
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_edited_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_edited_by")
    last_modified = models.DateTimeField(auto_now=True)
    # is_deleted = models.BooleanField(blank=False, null=False)
    # deleted_by = models.ForeignKey(User, on_delete=models.CASCADE))
    status = models.CharField(max_length=50, choices=ProjectStatusChoices.choices, default=ProjectStatusChoices.DISABLE)

    # class Meta:
    #     permissions = [('add_project', 'Can add project'),
    #                    ('change_project', 'Can change project'),
    #                    ('delete_project', 'Can delete project'),
    #                    ('view_project', 'Can view project'),
    #                    ('change_project_lock', 'Can change project lock status')
    #                    ]


class Home(models.Model):
    home_name = models.CharField(max_length=100, blank=False, null=False)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)
    owner_name = models.CharField(max_length=100, blank=True, null=True)
    owner_phone_number = models.CharField(max_length=100, blank=True, null=True)
    descriptions = models.CharField(max_length=1000, blank=True, null=True)
    parent_project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="homes")
    building = models.CharField(max_length=100, blank=True, null=True)
    floor = models.CharField(max_length=100, blank=True, null=True)
    unit = models.CharField(max_length=100, blank=True, null=True)

    # has_webapp = models.BooleanField(blank=False, null=False, default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='home_created_by')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_edited_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='home_edited_by')
    last_modified = models.DateTimeField(auto_now=True)
    # is_deleted = models.BooleanField(blank=False, null=False)
    # deleted_by = models.ForeignKey(User, on_delete=models.CASCADE))


class HomeUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='homeUser', related_query_name='homeUser')
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)
    parent_project = models.ForeignKey(Project, on_delete=models.CASCADE)
    parent_home = models.ForeignKey(Home, on_delete=models.CASCADE, related_name="homeUsers")
    # is_deleted = models.BooleanField(blank=False, null=False)
    # deleted_by = models.ForeignKey(User, on_delete=models.CASCADE))
    desc = models.CharField(max_length=500, blank=True)
    is_tablet_user = models.BooleanField(blank=False, null=False, default=False)
    is_web_app_user = models.BooleanField(blank=False, null=False, default=False)
    avatar = models.ImageField(upload_to="users_avatar/original_files/", blank=True, null=True)
    avatar_thumbnail = AdvanceThumbnailField(source_field='avatar', upload_to='users_avatar/thumbnail_files/',
                                             null=True, blank=True, size=(300, 300))

    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='homeUser_created_by')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_edited_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='homeUser_edited_by')
    last_modified = models.DateTimeField(auto_now=True)

    mqtt_client_id = models.CharField(max_length=100, blank=False, null=False, default=generate_rand_id_for_client)
    mqtt_username = models.CharField(max_length=100, blank=False, null=False, default=generate_random_username)
    mqtt_password = models.CharField(max_length=100, blank=False, null=False, default=generate_random_password)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         HomeUser.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     if hasattr(instance, 'homeUser'):
#         instance.homeUser.save()
#     else:
#         HomeUser.objects.create(user=instance)


class Tablet(models.Model):
    status = models.BooleanField(blank=False, null=False, default=False)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)
    descriptions = models.CharField(max_length=1000, blank=True, null=True)
    parent_project = models.ForeignKey(Project, on_delete=models.CASCADE)
    parent_home = models.ForeignKey(Home, on_delete=models.CASCADE, related_name="tablets")
    # if broker enabled in tablet, we need to ip address and port number of it to config controllers
    tablet_has_internal_mqtt_broker = models.BooleanField(blank=False, null=False, default=False)
    tablet_ip_address = models.GenericIPAddressField(protocol='both', unpack_ipv4=False, default='192.168.1.10')
    tablet_internal_mqtt_broker_port = models.IntegerField(blank=False, null=False, default=1883)
    tablet_internal_mqtt_broker_username = models.CharField(max_length=100, blank=True, null=True,
                                                            default=generate_random_username)
    tablet_internal_mqtt_broker_password = models.CharField(max_length=100, blank=True, null=True,
                                                            default=generate_random_password)


class Controller(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, blank=False, null=False)

    class ControllerStatusChoices(models.TextChoices):
        DISABLE = 'disable', 'disable'
        ENABLE = 'enable', 'enable'
        ERROR = 'error', 'error'

    class UartBaudRateChoices(models.TextChoices):
        BAUD_75 = '75', '75'
        BAUD_300 = '300', '300'
        BAUD_1200 = '1200', '1200'
        BAUD_2400 = '2400', '2400'
        BAUD_4800 = '4800', '4800'
        BAUD_9600 = '9600', '9600'
        BAUD_14400 = '14400', '14400'
        BAUD_19200 = '19200', '19200'
        BAUD_28800 = '28800', '28800'
        BAUD_38400 = '38400', '38400'
        BAUD_57600 = '57600', '57600'
        BAUD_115200 = '115200', '115200'
    
    class DataBitsChoices(models.TextChoices):
        DATA_BIT_5 = "5", "5"
        DATA_BIT_6 = "6", "6"
        DATA_BIT_7 = "7", "7"
        DATA_BIT_8 = "8", "8"
    
    class ParityChoices(models.TextChoices):
        NONE = "None", "None"
        ODD = "Odd", "Odd"
        EVEN = "Even", "Even"

    class StopBitsChoices(models.TextChoices):
        STOP_BIT_1 = "1", "1"
        STOP_BIT_2 = "2", "2"

    class FlowControlChoices(models.TextChoices):
        NONE = "None", "None"
        RTS_CTS = "RTS/CTS", "RTS/CTS"
        XON_XOFF = "Xon/Xoff", "Xon/Xoff"

codeBase/webServices/templates/dashboard/pages/home_wizard.html
{% extends 'dashboard/layouts/base.html' %}
{% load static %}

{% block title %}Home Wizard - {% endblock title %}
{% block body %}layout-fluid{% endblock body %}


{% block extrahead %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'font-awesome-6-pro-main/css/all.css' %}" />

{% endblock extrahead %}



{% block content %}

  <div class="page-wrapper">
    <!-- Page header -->
    <div class="page-header d-print-none">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Home Wizard
            </h2>
          </div>
        </div>
      </div>
    </div>
    <!-- Page body -->
    <div class="page-body">
      <div class="container-xl">

        <div class="row g-0" style="min-height: 30vw">
          <div class="col card d-none d-md-block border-end" style="max-width: 12%;margin-right: 2px">
            <div class="card-body">
              <h4 class="subheader">Home settings Menu</h4>
              <div class="list-group list-group-transparent">
{#                <a href="{% url 'dashboard:home_overview' project.uuid home.uuid %}" id="settings444"#}
{#                   class="list-group-item list-group-item-action d-flex align-items-center  border-bottom border-top">Overview</a>#}
                <a href="{% url 'dashboard:home_wizard_home_settings' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center {% if segment == 'settings' %}active{% endif %} border-bottom">General
                  settings</a>
                <a href="{% url 'dashboard:home_wizard_tablet_settings' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'tablet' %}active{% endif %}">Home
                  Tablet</a>
                <a href="{% url 'dashboard:home_wizard_all_controllers' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'controllers' %}active{% endif %}">Home
                  Controllers</a>
                <a href="{% url 'dashboard:home_wizard_all_zones' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'zones' %}active{% endif %}">Home
                  Zones</a>
                <a href="{% url 'dashboard:home_wizard_all_devices' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'devices' %}active{% endif %}">Home
                  Devices</a>
                <a href="{% url 'dashboard:home_wizard_all_ui_elements' project.uuid home.uuid %}" id="amir"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'ui' %}active{% endif %}">Home UI</a>
                <a href="{% url 'dashboard:home_wizard_all_users' project.uuid home.uuid %}"
                   class="list-group-item list-group-item-action d-flex align-items-center border-bottom {% if segment == 'home_users' %}active{% endif %}">Home Users</a>
                <!--                  <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">Billing & Invoices</a>-->
              </div>
              <!--                <h4 class="subheader mt-4">Experience</h4>-->
              <!--                <div class="list-group list-group-transparent">-->
              <!--                  <a href="#" class="list-group-item list-group-item-action">Give Feedback</a>-->
              <!--                </div>-->
            </div>
          </div>
          <div class="col card">

            {% block right_side_card_content %}{% endblock right_side_card_content %}

          </div>
        </div>
      </div>
    </div>
    {% include 'dashboard/includes/footer.html' %}
  </div>



  <div class="d-none" id="page-loader-section">
    <div class="page page-center">
      <div class="container container-slim py-4">
        <div class="d-flex flex-column align-items-center">
          <div class="mb-3">
            <a href="#" class="navbar-brand navbar-brand-autodark"><img src="{% static 'artiman-smart-logo.svg' %}" height="36" alt=""></a>
          </div>
          <div class="text-muted mb-3">Preparing application</div>
          <div class="progress progress-sm w-25">
            <div class="progress-bar progress-bar-indeterminate"></div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto">Bootstrap</strong>
        <small>Now</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">

      </div>
    </div>
  </div>

{% endblock content %}


{% block extrajs %}

  <script>
      document.addEventListener('load', () => {

              const toastLiveExample = document.getElementById('liveToast');
              const toast_body = document.getElementsByClassName("toast-body")[0];
              toast_body.innerHTML = "";
              const toast = new bootstrap.Toast(toastLiveExample);
              toast.show();

      })

  </script>





{#  <script>#}
{##}
{#      var amir_link = document.getElementById("amir");#}
{#      amir_link.addEventListener("click", function (event) {#}
{#          event.preventDefault();#}
{#          fetch("{% url 'dashboard:amir' %}")#}
{#              .then(response => response.json())#}
{#              .then(data => {#}
{#                  // data.rendered_template contains the rendered HTML string#}
{#                  document.getElementById('right_side_card').innerHTML = data.rendered_template;#}
{#              });#}
{#      })#}
{##}
{#      var settings_button_link = document.getElementById("settings");#}
{#      settings_button_link.addEventListener("click", function (event) {#}
{#          event.preventDefault();#}
{#          fetch("{% url 'dashboard:settings_button1' %}")#}
{#              .then(response => response.json())#}
{#              .then(data => {#}
{#                  // data.rendered_template contains the rendered HTML string#}
{#                  document.getElementById('right_side_card').innerHTML = data.rendered_template;#}
{#              });#}
{#      })#}
{##}
{#  </script>#}

{#  <script>#}
{#      /**#}
{#       * General-purpose fetch function with CSRF token handling for Django.#}
{#       *#}
{#       * @param {string} url - The URL to fetch.#}
{#       * @param {Object} options - Options for the fetch request.#}
{#       * @param {string} responseType - The type of response expected ('json', 'text', 'blob', 'arrayBuffer', 'formData').#}
{#       * @returns {Promise} - A promise that resolves with the response in the specified format.#}
{#       */#}
{#      async function fetchData(url, options = {}, responseType = 'json') {#}
{#          // Function to get CSRF token from the meta tag#}
{#          function getCsrfToken() {#}
{#              return document.querySelector('meta[name="csrf-token"]').getAttribute('content');#}
{#          }#}
{##}
{##}
{##}
{##}
{#          // Set default options and include CSRF token for non-GET requests#}
{#          const defaultOptions = {#}
{#              method: 'GET', // GET, POST, PUT, DELETE, etc.#}
{#              headers: {#}
{#                  'Content-Type': 'application/json', // Default header#}
{#              },#}
{#              body: null, // Body data (for POST, PUT requests)#}
{#              mode: 'cors', // 'cors', 'no-cors', 'same-origin'#}
{#              credentials: 'same-origin', // 'omit', 'same-origin', 'include'#}
{#              cache: 'no-cache', // 'default', 'no-cache', 'reload', 'force-cache', 'only-if-cached'#}
{#              redirect: 'follow', // 'follow', 'manual', 'error'#}
{#              referrer: 'no-referrer', // 'no-referrer', 'client'#}
{#              referrerPolicy: 'no-referrer', // 'no-referrer', 'no-referrer-when-downgrade', 'origin', etc.#}
{#              integrity: '', // Subresource integrity#}
{#              keepalive: false, // Keep the connection alive#}
{#              signal: null, // AbortController signal#}
{#          };#}
{##}
{#          // Add CSRF token to headers for methods other than GET#}
{#          if (options.method && options.method.toUpperCase() !== 'GET') {#}
{#              defaultOptions.headers['X-CSRFToken'] = getCsrfToken();#}
{#              const form = document.getElementById('home_setting_form');#}
{#              const formData = new FormData(form);#}
{#              defaultOptions.body = formData;#}
{#          }#}
{##}
{#          // Merge user options with default options#}
{#          const finalOptions = {...defaultOptions, ...options};#}
{#          console.log(finalOptions)#}
{##}
{##}
{##}
{#          try {#}
{#              const response = await fetch(url, finalOptions);#}
{##}
{#              if (!response.ok) {#}
{#                  throw new Error(`HTTP error! status: ${response.status}`);#}
{#              }#}
{##}
{#              switch (responseType.toLowerCase()) {#}
{#                  case 'json':#}
{#                      return await response.json();#}
{#                  case 'text':#}
{#                      return await response.text();#}
{#                  case 'blob':#}
{#                      return await response.blob();#}
{#                  case 'arraybuffer':#}
{#                      return await response.arrayBuffer();#}
{#                  case 'formdata':#}
{#                      return await response.formData();#}
{#                  default:#}
{#                      throw new Error('Unsupported response type');#}
{#              }#}
{#          } catch (error) {#}
{#              console.error('Fetch error:', error);#}
{#              throw error;#}
{#          }#}
{#      }#}
{##}
{##}
      {#// Example usage:#}
      {#fetchData('https://jsonplaceholder.typicode.com/posts', {method: 'GET'}, 'json')#}
      {#    .then(data => console.log(data))#}
      {#    .catch(error => console.error('Error:', error));#}
      {##}
      {#fetchData('https://example.com/api/endpoint', {method: 'POST', body: JSON.stringify({key: 'value'})}, 'json')#}
      {#    .then(data => console.log(data))#}
      {#    .catch(error => console.error('Error:', error));#}
{#  </script>#}
{##}
{#  <script>#}
{#  function show_page_loader_section(){#}
{#      const right_side_card = document.getElementById("right_side_card");#}
{#      right_side_card.innerHTML = document.getElementById("page-loader-section").innerHTML;#}
{#  }#}
{#  </script>#}
{##}
{#  <script>#}
{#    function load_page(url, options={}, responseType = 'json'){#}
{#        show_page_loader_section();#}
{#        fetchData(url, options, responseType)#}
{#        .then(data =>{#}
{#            switch (responseType.toLowerCase()) {#}
{#                  case 'json':#}
{#                      console.log(data, responseType);#}
{#                      document.getElementById('right_side_card').innerHTML = data.rendered_template;#}
{#                      break;#}
{#                  case 'text':#}
{#                      console.log(data, responseType);#}
{#                      break;#}
{#                  case 'blob':#}
{#                      console.log(data, responseType);#}
{#                      break;#}
{#                  case 'arraybuffer':#}
{#                      console.log(data, responseType);#}
{#                      break;#}
{#                  case 'formdata':#}
{#                      console.log(data, responseType);#}
{#                      break;#}
{#              }#}
{##}
{#        })#}
{#        .catch(error => console.error('Error:', error));#}
{##}
{#    }#}
{#    {% url 'dashboard:amir' %}#}
{#    load_page("{% url 'dashboard:home_wizard_home_settings' project.uuid home.uuid %}",{method: 'GET'});#}
{#  </script>#}

{% endblock extrajs %}